In [1]:
!pip install numpy

In [3]:
import numpy as np

# Create

In [5]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [6]:
data

array([[[0.02489491, 0.67420627, 0.22759863, 0.25650418],
        [0.92608213, 0.55569526, 0.41433874, 0.39691591],
        [0.1364949 , 0.06157732, 0.69232455, 0.79341487]],

       [[0.03453471, 0.60919033, 0.78774255, 0.65316448],
        [0.7577587 , 0.12307281, 0.35255757, 0.08752243],
        [0.29182753, 0.97902353, 0.93205301, 0.48402744]]])

In [7]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [8]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [9]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [10]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [11]:
type(arr)

numpy.ndarray

# Read

In [12]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [13]:
size

24

In [14]:
types

dtype('float64')

In [15]:
# Slicing
arr = data[0]
slicer = data[0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [16]:
reverse

array([[0.03453471, 0.60919033, 0.78774255, 0.65316448],
       [0.7577587 , 0.12307281, 0.35255757, 0.08752243],
       [0.29182753, 0.97902353, 0.93205301, 0.48402744]])

In [17]:
arr

array([[0.02489491, 0.67420627, 0.22759863, 0.25650418],
       [0.92608213, 0.55569526, 0.41433874, 0.39691591],
       [0.1364949 , 0.06157732, 0.69232455, 0.79341487]])

In [18]:
slicer

array([[[0.02489491, 0.67420627, 0.22759863, 0.25650418],
        [0.92608213, 0.55569526, 0.41433874, 0.39691591],
        [0.1364949 , 0.06157732, 0.69232455, 0.79341487]],

       [[0.03453471, 0.60919033, 0.78774255, 0.65316448],
        [0.7577587 , 0.12307281, 0.35255757, 0.08752243],
        [0.29182753, 0.97902353, 0.93205301, 0.48402744]]])

In [19]:
singleval

0.0248949075311945

# Update

# Delete